apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-order-app
  labels:
    app: food-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-order
  template:
    metadata:
      labels:
        app: food-order
    spec:
      containers:
      - name: food-order
        imagePullPolicy: Always
        image: food-order-image
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: food-order
spec:
  selector:
    app: food-order
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
